import { Body, Controller, Get, HttpException, Post, Query, Req, Res } from '@nestjs/common';
import { ApiBearerAuth, ApiBody, ApiHeader, ApiOperation, ApiParam, ApiQuery, ApiResponse, ApiTags } from '@nestjs/swagger';
import type { Response } from 'express';
import { createHash, randomUUID } from 'node:crypto';
import { Roles } from './auth/auth.decorators';
import type { AuthenticatedRequest } from './auth/auth.types';
import { RedisService } from './redis.service';
import { CreateOrderDto, ListOrdersQueryDto } from './validation.dto';

@ApiTags('Public API')
@ApiBearerAuth()
@ApiHeader({ name: 'x-request-id', required: false, description: 'Request identifier; generated by the gateway when omitted.' })
@ApiHeader({ name: 'x-correlation-id', required: false, description: 'Correlation identifier; defaults to the request identifier.' })
@Controller()
export class GatewayProxyController {
  private readonly orderServiceUrl = process.env.ORDER_SERVICE_URL ?? 'http://localhost:3001';
  private readonly paymentServiceUrl = process.env.PAYMENT_SERVICE_URL ?? 'http://localhost:3002';
  private readonly workerServiceUrl = process.env.WORKER_SERVICE_URL ?? 'http://localhost:3003';

  constructor(private readonly redis: RedisService) {}

  @Post('orders')
  @Roles('CUSTOMER')
  @ApiOperation({ summary: 'Create an order and start asynchronous payment processing' })
  @ApiHeader({ name: 'idempotency-key', required: true, description: 'Reuse with the same body to receive the original response.' })
  @ApiBody({ required: true, schema: { type: 'object', required: ['items', 'currency'], properties: {
    items: { type: 'array', minItems: 1, maxItems: 50, items: { type: 'object', required: ['productId', 'quantity', 'unitAmount'], properties: {
      productId: { type: 'string', example: 'sku_123' }, quantity: { type: 'integer', minimum: 1, example: 2 }, unitAmount: { type: 'integer', minimum: 0, description: 'Minor currency units', example: 1500 },
    } } },
    currency: { type: 'string', pattern: '^[A-Za-z]{3}$', example: 'BDT' },
  } } })
  @ApiResponse({ status: 202, description: 'Order accepted; payment processing continues asynchronously.', schema: { type: 'object', properties: {
    id: { type: 'string', example: 'ord_123' }, userId: { type: 'string', example: 'usr_dev' }, items: { type: 'array', items: { type: 'object' } },
    totalAmount: { type: 'number', example: 3000 }, currency: { type: 'string', example: 'BDT' }, status: { type: 'string', example: 'PENDING_PAYMENT' },
    paymentId: { type: 'string', nullable: true }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' },
  } } })
  @ApiResponse({ status: 400, description: 'Invalid order or missing Idempotency-Key.' })
  @ApiResponse({ status: 401, description: 'A valid bearer token is required.' })
  @ApiResponse({ status: 429, description: 'Write rate limit exceeded.' })
  @ApiResponse({ status: 409, description: 'Idempotency key reused with a different request.' })
  @ApiResponse({ status: 503, description: 'Downstream service unavailable.' })
  createOrder(@Body() body: CreateOrderDto, @Req() request: AuthenticatedRequest, @Res() response: Response) {
    request.body = body;
    return this.forward(request, response, this.orderServiceUrl);
  }

  @Get('orders')
  @ApiOperation({ summary: 'List the current user’s orders' })
  @ApiQuery({ name: 'limit', required: false, description: 'Maximum number of results (1–100).', example: 20 })
  @ApiResponse({ status: 200, description: 'Orders, newest first.' })
  @ApiResponse({ status: 400, description: 'Invalid limit.' })
  @ApiResponse({ status: 401, description: 'A valid bearer token is required.' })
  @ApiResponse({ status: 429, description: 'Read rate limit exceeded.' })
  @ApiResponse({ status: 503, description: 'Downstream service unavailable.' })
  listOrders(@Query() query: ListOrdersQueryDto, @Req() request: AuthenticatedRequest, @Res() response: Response) {
    void query;
    return this.forward(request, response, this.orderServiceUrl);
  }

  @Get('orders/:id')
  @ApiOperation({ summary: 'Get an order owned by the current user' })
  @ApiParam({ name: 'id', example: 'ord_123' })
  @ApiResponse({ status: 200, description: 'Order details and current payment status.' })
  @ApiResponse({ status: 404, description: 'Order not found for this user.' })
  @ApiResponse({ status: 401, description: 'A valid bearer token is required.' })
  @ApiResponse({ status: 503, description: 'Downstream service unavailable.' })
  proxyOrder(@Req() request: AuthenticatedRequest, @Res() response: Response) {
    return this.forward(request, response, this.orderServiceUrl);
  }

  @Get('payments/:id')
  @ApiOperation({ summary: 'Get a payment owned by the current user' })
  @ApiParam({ name: 'id', example: 'pay_123' })
  @ApiResponse({ status: 200, description: 'Payment details and processing attempt count.' })
  @ApiResponse({ status: 404, description: 'Payment not found for this user.' })
  @ApiResponse({ status: 401, description: 'A valid bearer token is required.' })
  @ApiResponse({ status: 503, description: 'Downstream service unavailable.' })
  proxyPayment(@Req() request: AuthenticatedRequest, @Res() response: Response) {
    return this.forward(request, response, this.paymentServiceUrl);
  }

  @Get('admin/dlq')
  @Roles('ADMIN')
  @ApiOperation({ summary: 'List pending dead-letter payment records (admin only)' })
  @ApiResponse({ status: 200, description: 'Up to 100 pending DLQ records.' })
  @ApiResponse({ status: 401, description: 'A valid bearer token is required.' })
  @ApiResponse({ status: 403, description: 'Admin role required.' })
  proxyDlq(@Req() request: AuthenticatedRequest, @Res() response: Response) {
    return this.forward(request, response, this.workerServiceUrl, this.adminHeaders(request));
  }

  @Post('admin/dlq/:id/reprocess')
  @Roles('ADMIN')
  @ApiOperation({ summary: 'Requeue a dead-letter payment request (admin only)' })
  @ApiParam({ name: 'id', example: 'dlq_123' })
  @ApiResponse({ status: 200, description: 'DLQ entry requeued using the original payment/provider identity.' })
  @ApiResponse({ status: 403, description: 'Admin role required.' })
  @ApiResponse({ status: 404, description: 'Unprocessed DLQ entry not found.' })
  @ApiResponse({ status: 401, description: 'A valid bearer token is required.' })
  proxyReprocessDlq(@Req() request: AuthenticatedRequest, @Res() response: Response) {
    return this.forward(request, response, this.workerServiceUrl, this.adminHeaders(request));
  }

  private adminHeaders(request: AuthenticatedRequest) {
    return { 'x-admin-token': process.env.DLQ_ADMIN_TOKEN ?? 'local-dlq-admin-token', 'x-admin-id': request.user.sub };
  }

  private async forward(request: AuthenticatedRequest, response: Response, serviceUrl: string, extraHeaders: Record<string, string> = {}) {
    const requestId = request.header('x-request-id') ?? randomUUID();
    const correlationId = request.header('x-correlation-id') ?? requestId;
    const headers: Record<string, string> = {
      'x-request-id': requestId,
      'x-correlation-id': correlationId,
      'x-user-id': request.user.sub,
      'x-user-role': request.user.role,
      ...extraHeaders,
    };
    const idempotencyKey = request.header('idempotency-key');
    if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
    const contentType = request.header('content-type');
    if (contentType) headers['content-type'] = contentType;
    const method = request.method.toUpperCase();
    const body = method === 'GET' || method === 'HEAD' ? undefined : JSON.stringify(request.body ?? {});
    const skipCache = request.header('cache-control')?.toLowerCase().includes('no-cache') ?? false;
    const cacheKey = method === 'GET' && !skipCache && this.isCacheableRead(request.originalUrl)
      ? this.cacheKey(request.user.sub, request.originalUrl)
      : undefined;

    if (cacheKey) {
      try {
        const cached = await this.redis.get(cacheKey);
        if (cached) {
          const entry = JSON.parse(cached) as { body: string; contentType: string };
          response.status(200);
          response.setHeader('content-type', entry.contentType);
          response.setHeader('x-request-id', requestId);
          response.setHeader('x-correlation-id', correlationId);
          response.setHeader('x-cache', 'HIT');
          return response.send(entry.body);
        }
      } catch { /* Redis cache failures fall through to the source of truth. */ }
    }

    try {
      const upstream = await fetch(`${serviceUrl}${request.originalUrl.replace(/^\/api/, '')}`, {
        method,
        headers,
        body,
        signal: AbortSignal.timeout(5000),
      });
      response.status(upstream.status);
      response.setHeader('x-request-id', requestId);
      response.setHeader('x-correlation-id', correlationId);
      const upstreamContentType = upstream.headers.get('content-type');
      if (upstreamContentType) response.setHeader('content-type', upstreamContentType);
      const responseBody = await upstream.text();
      response.setHeader('x-cache', 'MISS');
      if (cacheKey && upstream.status === 200 && upstreamContentType?.includes('application/json')) {
        try {
          await this.redis.set(cacheKey, JSON.stringify({ body: responseBody, contentType: upstreamContentType }), 10);
          if (request.originalUrl.split('?')[0] === '/api/orders') {
            const userKey = this.cacheUserKey(request.user.sub);
            const indexKey = `cache:orders:index:${userKey}`;
            await this.redis.sadd(indexKey, cacheKey);
            await this.redis.expire(indexKey, 10);
          }
        } catch { /* A cache write failure does not fail a successful read. */ }
      }
      if (method === 'POST' && request.originalUrl.split('?')[0] === '/api/orders' && upstream.status >= 200 && upstream.status < 300) {
        try {
          const indexKey = `cache:orders:index:${this.cacheUserKey(request.user.sub)}`;
          const cachedOrderLists = await this.redis.smembers(indexKey);
          await this.redis.del(...cachedOrderLists, indexKey);
        } catch { /* Cached entries expire after ten seconds. */ }
      }
      response.send(responseBody);
    } catch {
      throw new HttpException({ error: { code: 'UPSTREAM_UNAVAILABLE', message: 'A downstream service is unavailable', requestId } }, 503);
    }
  }

  private isCacheableRead(url: string) {
    return /^\/api\/(?:orders(?:\/[^/?]+)?|payments\/[^/?]+)(?:\?.*)?$/.test(url);
  }

  private cacheKey(userId: string, url: string) {
    const user = this.cacheUserKey(userId);
    const request = createHash('sha256').update(url).digest('hex');
    return `cache:api:${user}:${request}`;
  }

  private cacheUserKey(userId: string) { return createHash('sha256').update(userId).digest('hex'); }
}
