import { Controller, Get, HttpException, Post, Req, Res } from '@nestjs/common';
import { ApiBody, ApiHeader, ApiOperation, ApiParam, ApiQuery, ApiResponse, ApiTags } from '@nestjs/swagger';
import type { Request, Response } from 'express';
import { randomUUID } from 'node:crypto';

@ApiTags('Public API')
@Controller()
export class GatewayProxyController {
  private readonly orderServiceUrl = process.env.ORDER_SERVICE_URL ?? 'http://localhost:3001';
  private readonly paymentServiceUrl = process.env.PAYMENT_SERVICE_URL ?? 'http://localhost:3002';

  @Post('orders')
  @ApiOperation({ summary: 'Create an order and start asynchronous payment processing' })
  @ApiHeader({ name: 'x-user-id', required: false, description: 'Development identity forwarded to the Order Service.', example: 'usr_dev' })
  @ApiHeader({ name: 'idempotency-key', required: true, description: 'Reuse with the same body to receive the original response.' })
  @ApiHeader({ name: 'x-request-id', required: false, description: 'Request identifier; generated by the gateway when omitted.' })
  @ApiHeader({ name: 'x-correlation-id', required: false, description: 'Correlation identifier; defaults to the request identifier.' })
  @ApiBody({ required: true, schema: { type: 'object', required: ['items', 'currency'], properties: {
    items: { type: 'array', minItems: 1, maxItems: 50, items: { type: 'object', required: ['productId', 'quantity', 'unitAmount'], properties: {
      productId: { type: 'string', example: 'sku_123' }, quantity: { type: 'integer', minimum: 1, example: 2 }, unitAmount: { type: 'integer', minimum: 0, description: 'Minor currency units', example: 1500 },
    } } },
    currency: { type: 'string', pattern: '^[A-Za-z]{3}$', example: 'BDT' },
  } } })
  @ApiResponse({ status: 202, description: 'Order accepted; payment processing continues asynchronously.', schema: { type: 'object', properties: {
    id: { type: 'string', example: 'ord_123' }, userId: { type: 'string', example: 'usr_dev' }, items: { type: 'array', items: { type: 'object' } },
    totalAmount: { type: 'number', example: 3000 }, currency: { type: 'string', example: 'BDT' }, status: { type: 'string', example: 'PENDING_PAYMENT' },
    paymentId: { type: 'string', nullable: true }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' },
  } } })
  @ApiResponse({ status: 400, description: 'Invalid order or missing Idempotency-Key.' })
  @ApiResponse({ status: 409, description: 'Idempotency key reused with a different request.' })
  @ApiResponse({ status: 503, description: 'Downstream service unavailable.' })
  createOrder(@Req() request: Request, @Res() response: Response) {
    return this.forward(request, response, this.orderServiceUrl);
  }

  @Get('orders')
  @ApiOperation({ summary: 'List the current user’s orders' })
  @ApiHeader({ name: 'x-user-id', required: false, description: 'Development identity forwarded to the Order Service.', example: 'usr_dev' })
  @ApiQuery({ name: 'limit', required: false, description: 'Maximum number of results (1–100).', example: 20 })
  @ApiResponse({ status: 200, description: 'Orders, newest first.' })
  @ApiResponse({ status: 400, description: 'Invalid limit.' })
  @ApiResponse({ status: 503, description: 'Downstream service unavailable.' })
  listOrders(@Req() request: Request, @Res() response: Response) {
    return this.forward(request, response, this.orderServiceUrl);
  }

  @Get('orders/:id')
  @ApiOperation({ summary: 'Get an order owned by the current user' })
  @ApiParam({ name: 'id', example: 'ord_123' })
  @ApiHeader({ name: 'x-user-id', required: false, description: 'Development identity forwarded to the Order Service.', example: 'usr_dev' })
  @ApiResponse({ status: 200, description: 'Order details and current payment status.' })
  @ApiResponse({ status: 404, description: 'Order not found for this user.' })
  @ApiResponse({ status: 503, description: 'Downstream service unavailable.' })
  proxyOrder(@Req() request: Request, @Res() response: Response) {
    return this.forward(request, response, this.orderServiceUrl);
  }

  @Get('payments/:id')
  @ApiOperation({ summary: 'Get a payment owned by the current user' })
  @ApiParam({ name: 'id', example: 'pay_123' })
  @ApiHeader({ name: 'x-user-id', required: false, description: 'Development identity forwarded to the Payment Service.', example: 'usr_dev' })
  @ApiResponse({ status: 200, description: 'Payment details and processing attempt count.' })
  @ApiResponse({ status: 404, description: 'Payment not found for this user.' })
  @ApiResponse({ status: 503, description: 'Downstream service unavailable.' })
  proxyPayment(@Req() request: Request, @Res() response: Response) {
    return this.forward(request, response, this.paymentServiceUrl);
  }

  private async forward(request: Request, response: Response, serviceUrl: string) {
    const requestId = request.header('x-request-id') ?? randomUUID();
    const correlationId = request.header('x-correlation-id') ?? requestId;
    const headers: Record<string, string> = {
      'x-request-id': requestId,
      'x-correlation-id': correlationId,
      'x-user-id': request.header('x-user-id') ?? 'usr_dev',
    };
    const idempotencyKey = request.header('idempotency-key');
    if (idempotencyKey) headers['idempotency-key'] = idempotencyKey;
    const contentType = request.header('content-type');
    if (contentType) headers['content-type'] = contentType;
    const method = request.method.toUpperCase();
    const body = method === 'GET' || method === 'HEAD' ? undefined : JSON.stringify(request.body ?? {});

    try {
      const upstream = await fetch(`${serviceUrl}${request.originalUrl.replace(/^\/api/, '')}`, {
        method,
        headers,
        body,
        signal: AbortSignal.timeout(5000),
      });
      response.status(upstream.status);
      response.setHeader('x-request-id', requestId);
      response.setHeader('x-correlation-id', correlationId);
      const upstreamContentType = upstream.headers.get('content-type');
      if (upstreamContentType) response.setHeader('content-type', upstreamContentType);
      response.send(await upstream.text());
    } catch {
      throw new HttpException({ error: { code: 'UPSTREAM_UNAVAILABLE', message: 'A downstream service is unavailable', requestId } }, 503);
    }
  }
}
